# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FirgIeFx-ldF9Whz8bZgHtKtUVcZotB5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans



x = np.array([
    [9,3],
    [8,4],
    [4,6],
    [8,5],
    [2,5],
    [3,8],
    [5,8],
    [4,4],
    [10,4],
    [9,6],])

#plt.scatter(x[:,0],x[:,1],label='true function' )
kMeans= KMeans(n_clusters=3)
kMeans.fit(x)
print(kMeans.cluster_centers_)
print('The Points')
print(kMeans.labels_)
#plt.scatter(x[:,0],x[:,1],label='rainbow' )